/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class poca_cn_com_ndkjnidemo_jniUtils_StringUtils */

#ifndef _Included_poca_cn_com_ndkjnidemo_jniUtils_StringUtils
#define _Included_poca_cn_com_ndkjnidemo_jniUtils_StringUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     poca_cn_com_ndkjnidemo_jniUtils_StringUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_poca_cn_com_ndkjnidemo_jniUtils_StringUtils_getStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
